---
environment: production
chdir: /path/to/app/
address: 127.0.0.1
user: root
group: root
port: 4567
pid: /path/to/app/tmp/thin.pid
rackup: /path/to/app/config/rackup.ru
log: /path/to/app/logs/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true